In [1]:
!pip install pyvinecopulib

In [2]:
import pyvinecopulib as pv
import numpy as np


pv.Bicop() 

help(pv.Bicop)

Help on class Bicop in module pyvinecopulib:

class Bicop(pybind11_builtins.pybind11_object)
 |  A class for bivariate copula models.
 |  
 |  The copula model is fully characterized by the family, rotation, and
 |  parameters.
 |  
 |  Method resolution order:
 |      Bicop
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: pyvinecopulib.Bicop, family: pyvinecopulib.BicopFamily = <BicopFamily.indep: 0>, rotation: int = 0, parameters: numpy.ndarray[numpy.float64[m, n]] = array([], shape=(0, 0), dtype=float64), var_types: List[str] = ['c', 'c']) -> None
 |      
 |      Instantiates a specific bivariate copula model.
 |      
 |      Parameter ``family``:
 |          The copula family.
 |      
 |      Parameter ``rotation``:
 |          The rotation of the copula; one of 0, 90, 180, or 270 (for
 |          Independence, G

In [3]:
#Create a t copula with correlation of 0.5 and 4 degrees of freedom
cop = pv.Bicop(family=pv.BicopFamily.student, rotation=0, parameters=[0.5, 4])
cop

<pyvinecopulib.Bicop>
Student, parameters = 0.5
  4

In [4]:
help(pv.Bicop.pdf)

Help on instancemethod in module pyvinecopulib:

pdf(...)
    pdf(self: pyvinecopulib.Bicop, u: numpy.ndarray[numpy.float64[m, n]]) -> numpy.ndarray[numpy.float64[m, 1]]
    
    Evaluates the copula density.
    
    The copula density is defined as joint density divided by marginal
    densities, irrespective of variable types.
    
    Parameter ``u``:
        An :math:`n \times (2 + k)` matrix of observations contained in
        :math:`(0, 1)`, where :math:`k` is the number of discrete
        variables.
    
    Returns:
        The copula density evaluated at ``u``.



In [5]:
# simulate datapoints
u = cop.simulate(n=10, seeds=[1])

# functions that can be used on copula
fcts = [cop.pdf, cop.cdf,
        cop.hfunc1, cop.hfunc2,
        cop.hinv1, cop.hinv2,
        cop.loglik, cop.aic, cop.bic]

[f(u) for f in fcts]



[array([1.15651594, 0.83673524, 0.33015689, 2.33625114, 1.23099228,
        1.75986902, 0.71551288, 0.93307286, 1.11592899, 1.09654069]),
 array([0.27188078, 0.25901473, 0.07757715, 0.03260215, 0.60326414,
        0.0556768 , 0.12511077, 0.52495921, 0.45094881, 0.27978662]),
 array([0.28412845, 0.16894735, 0.9842996 , 0.3287706 , 0.43042859,
        0.15044619, 0.80489141, 0.91343945, 0.80328973, 0.26223844]),
 array([0.66347522, 0.82759246, 0.02849788, 0.14270918, 0.86172074,
        0.4021135 , 0.07566623, 0.30477093, 0.35306236, 0.70677928]),
 array([0.4160921 , 0.4336959 , 0.85748522, 0.03856737, 0.80521298,
        0.07696747, 0.36348105, 0.82554684, 0.70555113, 0.43136434]),
 array([0.47108595, 0.55640704, 0.23223492, 0.03798033, 0.8369594 ,
        0.08218761, 0.23906983, 0.76365192, 0.64740506, 0.49886715]),
 0.2784045757848149,
 3.44319084843037,
 4.048361034418462]

In [6]:
# if family is known we can fit a copula on data in the following way:
u = cop.simulate(n=1000, seeds=[1, 2, 3])
print(u)
# Create a new object an sets its parameters by fitting afterwards
cop2 = pv.Bicop(pv.BicopFamily.student)
cop2.fit(data=u)
print(cop2)


# Otherwise, define first an object to control the fits:
#    - pv.FitControlsBicop objects store the controls
#    - here, we only restrict the parametric family
#    - see help(pv.FitControlsBicop) for more details
# Then, create a copula from the data
controls = pv.FitControlsBicop(family_set=[pv.BicopFamily.student])
print(controls)
cop2 = pv.Bicop(data=u, controls=controls)
print(cop2)

[[0.1638618  0.02865033]
 [0.90118677 0.83527094]
 [0.62193432 0.39461854]
 ...
 [0.88216762 0.95139064]
 [0.80396499 0.21342001]
 [0.91571645 0.07045588]]
<pyvinecopulib.Bicop>
Student, parameters = 0.515883
 4.13667
<pyvinecopulib.FitControlsBicop>
Family set: Student
Parametric method: mle
Nonparametric method: quadratic
Nonparametric multiplier: 1
Weights: no
Selection criterion: bic
Preselect families: yes
mBIC prior probability: 0.9
Number of threads: 1

<pyvinecopulib.Bicop>
Student, parameters = 0.515883
 4.13667


In [7]:
# if the family is unknown we do the following:
cop3 = pv.Bicop(data=u)
print(cop3)

<pyvinecopulib.Bicop>
Student, parameters = 0.515883
 4.13667


**Vine COPULAS**

In [8]:
help(pv.Bicop)

Help on class Bicop in module pyvinecopulib:

class Bicop(pybind11_builtins.pybind11_object)
 |  A class for bivariate copula models.
 |  
 |  The copula model is fully characterized by the family, rotation, and
 |  parameters.
 |  
 |  Method resolution order:
 |      Bicop
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: pyvinecopulib.Bicop, family: pyvinecopulib.BicopFamily = <BicopFamily.indep: 0>, rotation: int = 0, parameters: numpy.ndarray[numpy.float64[m, n]] = array([], shape=(0, 0), dtype=float64), var_types: List[str] = ['c', 'c']) -> None
 |      
 |      Instantiates a specific bivariate copula model.
 |      
 |      Parameter ``family``:
 |          The copula family.
 |      
 |      Parameter ``rotation``:
 |          The rotation of the copula; one of 0, 90, 180, or 270 (for
 |          Independence, G

Working with vine copulashelp(pv.Vinecop)

In [9]:
help(pv.Vinecop)

Help on class Vinecop in module pyvinecopulib:

class Vinecop(pybind11_builtins.pybind11_object)
 |  A class for vine copula models.
 |  
 |  A vine copula model is characterized by its structure (see
 |  ``RVineStructure`` objects) and the pair-copulas.
 |  
 |  Method resolution order:
 |      Vinecop
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: pyvinecopulib.Vinecop, d: int) -> None
 |      
 |      Instantiates a D-vine with all pair-copulas set to independence.
 |      
 |      Parameter ``d``:
 |          The dimension (= number of variables) of the model.
 |      
 |      2. __init__(self: pyvinecopulib.Vinecop, structure: pyvinecopulib.RVineStructure, pair_copulas: List[List[pyvinecopulib.Bicop]] = [], var_types: List[str] = []) -> None
 |      
 |      Instantiates an arbitrary vine copula model.
 |      
 

In [10]:
# Specify pair-copulas
bicop = pv.Bicop(pv.BicopFamily.bb1, 90, [3, 2])
pcs = [[bicop, bicop], [bicop]]

In [11]:
# Specify R-vine matrix
mat = np.array([[1, 1, 1], [2, 2, 0], [3, 0, 0]])

In [12]:
# Set-up a vine copula
cop = pv.Vinecop(mat, pcs)
print(cop)


<pyvinecopulib.Vinecop>
** Tree: 0
3,1 <-> BB1 90°, parameters = 3
2
2,1 <-> BB1 90°, parameters = 3
2
** Tree: 1
3,2 | 1 <-> BB1 90°, parameters = 3
2



In [13]:
# testing methods that work on vinecopulas
u = cop.simulate(n=10, seeds=[1, 2, 3])
fcts = [cop.pdf, cop.rosenblatt, cop.inverse_rosenblatt,
        cop.loglik, cop.aic, cop.bic]
[f(u) for f in fcts]

[array([ 44.67583001,  54.34974545,  29.84989695,  19.18643731,
        199.72159236, 944.18332674,  21.78049474,  43.78532554,
          9.10911159,  13.39339764]),
 array([[0.1638618 , 0.8170847 , 0.12668051],
        [0.90118677, 0.11345478, 0.2222099 ],
        [0.62193432, 0.12286857, 0.39604429],
        [0.6902412 , 0.78638305, 0.37455509],
        [0.13685699, 0.10872534, 0.2777274 ],
        [0.03952828, 0.35645124, 0.06597532],
        [0.48023317, 0.77472657, 0.72886036],
        [0.19787956, 0.90877192, 0.60171   ],
        [0.85523898, 0.76413881, 0.04961411],
        [0.17627362, 0.77807695, 0.03875948]]),
 array([[0.1638618 , 0.8728502 , 0.79397093],
        [0.90118677, 0.03148971, 0.30865931],
        [0.62193432, 0.28213894, 0.46366853],
        [0.6902412 , 0.28590505, 0.30879851],
        [0.13685699, 0.88594611, 0.84611164],
        [0.03952828, 0.97430917, 0.95100319],
        [0.48023317, 0.53494551, 0.47865733],
        [0.19787956, 0.84458738, 0.75111263],
    

In [14]:
# fitting a copula when we know the family 
# and structure
u = cop.simulate(n=1000, seeds=[1, 2, 3])

# Define first an object to control the fits:
#    - pv.FitControlsVinecop objects store the controls
#    - here, we only restrict the parametric family
#    - see help(pv.FitControlsVinecop) for more details
controls = pv.FitControlsVinecop(family_set=[pv.BicopFamily.bb1])
print(controls)

<pyvinecopulib.FitControlsVinecop>
Family set: BB1
Parametric method: mle
Nonparametric method: quadratic
Nonparametric multiplier: 1
Weights: no
Selection criterion: bic
Preselect families: yes
mBIC prior probability: 0.9
Truncation level: none (default)
Tree criterion: tau
Threshold: 0
Select truncation level: no
Select threshold: no
Show trace: no
Number of threads: 1



In [15]:
# Create a new object an select family and parameters by fitting to data
cop2 = pv.Vinecop(mat, pcs)
cop2.select(data=u, controls=controls)
print(cop2)

<pyvinecopulib.Vinecop>
** Tree: 0
3,1 <-> BB1 90°, parameters = 2.92727
2.02245
2,1 <-> BB1 90°, parameters = 2.98212
2.04269
** Tree: 1
3,2 | 1 <-> BB1 90°, parameters = 2.72951
 2.0422



In [16]:
# Otherwise, create directly from data
cop2 = pv.Vinecop(data=u, matrix=mat, controls=controls)
print(cop2)

<pyvinecopulib.Vinecop>
** Tree: 0
3,1 <-> BB1 90°, parameters = 2.92727
2.02245
2,1 <-> BB1 90°, parameters = 2.98212
2.04269
** Tree: 1
3,2 | 1 <-> BB1 90°, parameters = 2.72951
 2.0422



When nothing is known, there are also two ways to fit a copula...



In [17]:
# Create a new object and select strucutre, family, and parameters
cop3 = pv.Vinecop(d=3)
cop3.select(data=u)
print(cop3)

# Otherwise, create directly from data
cop3 = pv.Vinecop(data=u)
print(cop3)

<pyvinecopulib.Vinecop>
** Tree: 0
2,1 <-> BB1 90°, parameters = 2.98212
2.04269
1,3 <-> BB6 90°, parameters = 1.54273
3.96417
** Tree: 1
2,3 | 1 <-> BB7 90°, parameters =  5.2555
2.34762

<pyvinecopulib.Vinecop>
** Tree: 0
2,1 <-> BB1 90°, parameters = 2.98212
2.04269
1,3 <-> BB6 90°, parameters = 1.54273
3.96417
** Tree: 1
2,3 | 1 <-> BB7 90°, parameters =  5.2555
2.34762



In [18]:
# create a C-vine structure with root node 1 in first tree, 2 in second, ...
cvine = pv.CVineStructure([4, 3, 2, 1]) 
# specify pair-copulas in every tree
print(cvine)
tree1 = [pv.Bicop(pv.BicopFamily.gaussian, 0, [0.5]), 
         pv.Bicop(pv.BicopFamily.clayton, 0, [3]),
         pv.Bicop(pv.BicopFamily.student, 0, [0.4, 4])]
tree2 = [pv.Bicop(pv.BicopFamily.indep), 
         pv.Bicop(pv.BicopFamily.gaussian, 0, [0.5])]
tree3 = [pv.Bicop(pv.BicopFamily.gaussian)]
# instantiate C-vine copula model
cop = pv.Vinecop(cvine, [tree1, tree2, tree3])
print(cop)

<pyvinecopulib.CVineStructure>
1 1 1 1 
2 2 2 
3 3 
4 

<pyvinecopulib.Vinecop>
** Tree: 0
4,1 <-> Gaussian, parameters = 0.5
3,1 <-> Clayton, parameters = 3
2,1 <-> Student, parameters = 0.4
  4
** Tree: 1
4,2 | 1 <-> Independence
3,2 | 1 <-> Gaussian, parameters = 0.5
** Tree: 2
4,3 | 2,1 <-> Gaussian, parameters = 0



In [19]:
# Simulate some data
np.random.seed(1234)  # seed for the random generator
n = 1000  # number of observations
d = 5  # the dimension
mean = np.random.normal(size=d)  # mean vector
cov = np.random.normal(size=(d, d))  # covariance matrix
cov = np.dot(cov.transpose(), cov)  # make it non-negative definite
x = np.random.multivariate_normal(mean, cov, n)


In [20]:
# Transform copula data using the empirical distribution
u = pv.to_pseudo_obs(x)

In [22]:

# Fit a Gaussian vine
# (i.e., properly specified since the data is multivariate normal)
controls = pv.FitControlsVinecop(family_set=[pv.BicopFamily.gaussian])
cop = pv.Vinecop(u, controls=controls)
cop

<pyvinecopulib.Vinecop>
** Tree: 0
3,1 <-> Gaussian, parameters = 0.396313
2,1 <-> Gaussian, parameters = 0.674068
4,1 <-> Gaussian, parameters = -0.611937
1,5 <-> Gaussian, parameters = -0.631672
** Tree: 1
3,2 | 1 <-> Gaussian, parameters = -0.741578
2,4 | 1 <-> Gaussian, parameters = -0.145053
4,5 | 1 <-> Gaussian, parameters = -0.804389
** Tree: 2
3,4 | 2,1 <-> Gaussian, parameters = -0.0470784
2,5 | 4,1 <-> Gaussian, parameters = -0.490632
** Tree: 3
3,5 | 4,2,1 <-> Gaussian, parameters = -0.0622675

In [24]:
# Sample from the copula
n_sim = 1000
u_sim = cop.simulate(n_sim, seeds=[1, 2, 3, 4])
u_sim

array([[0.43831965, 0.49878846, 0.55369009, 0.33930351, 0.83613548],
       [0.26291279, 0.23750598, 0.71229572, 0.42706282, 0.75958158],
       [0.157043  , 0.2172781 , 0.58560794, 0.66522508, 0.49475672],
       ...,
       [0.7252862 , 0.51867609, 0.97544295, 0.42210084, 0.18306158],
       [0.27902889, 0.54723187, 0.50661808, 0.966815  , 0.10108552],
       [0.02867689, 0.67022463, 0.00142254, 0.95684489, 0.74291997]])

In [26]:
# Transform back simulations to the original scale
x_sim = np.asarray([np.quantile(x[:, i], u_sim[:, i]) for i in range(0, d)])
x_sim

array([[ 0.1173705 , -0.54218953, -1.07174691, ...,  1.24933128,
        -0.48317612, -2.52830222],
       [-1.19869832, -2.45418844, -2.56119631, ..., -1.13294323,
        -1.04382129, -0.50328342],
       [ 1.53770499,  2.39888648,  1.70872456, ...,  5.57023779,
         1.27960565, -4.50177318],
       [-1.42791644, -0.77893263,  0.81842211, ..., -0.83434274,
         4.2516645 ,  3.92711962],
       [ 2.63535362,  1.69651834, -0.52164559, ..., -3.31098977,
        -4.63645311,  1.47939032]])

In [27]:
# Both the mean and covariance matrix look ok!
[mean, np.mean(x_sim, 1)]
[cov, np.cov(x_sim)]

[array([[ 2.37095772,  1.72011592,  1.34581349, -2.33400987, -3.1412032 ],
        [ 1.72011592,  2.77391072, -0.8386675 , -1.94255384, -3.0356469 ],
        [ 1.34581349, -0.8386675 ,  4.73656299, -1.11520579, -1.00737741],
        [-2.33400987, -1.94255384, -1.11520579,  6.17099976, -0.86804342],
        [-3.1412032 , -3.0356469 , -1.00737741, -0.86804342, 10.39309954]]),
 array([[ 2.22422017,  1.5946634 ,  1.44467283, -2.24840034, -2.86432409],
        [ 1.5946634 ,  2.56490065, -0.64236225, -1.88381331, -2.55280137],
        [ 1.44467283, -0.64236225,  4.48378773, -1.21625326, -1.35825765],
        [-2.24840034, -1.88381331, -1.21625326,  6.11239488, -1.14967754],
        [-2.86432409, -2.55280137, -1.35825765, -1.14967754,  9.93512784]])]